### PR TITLE
Static error pages

### PR DESCRIPTION
**Pull request by Mrinalsinghal**

### CODE REVIEW

**Comment by Ardnived** [comment]
@Mrinalsinghal I see that currently you have two 404.html files. What's the reason for that?

Also, I guess you ran into some issues with the `image_pack_tag`, but I think your change might break many other pages. The idea in general is to move away from using the `assets` folder and instead put images, css, and javascript in the new `frontend` folder. I think this might be the cause of your issue.

Everything in the `webpacker` branch which is still in the `assets` folder is legacy code and images which I intend to delete before merging it into master.

**Comment by Mrinalsinghal** [comment]
2 html were generated due to the gem `error_page_assets`, but now that we are not using it, i will go ahead and remove it. 

I am not sure about the issue regarding the image paths. For ex: I am getting Manifest error at `/meditations`:

> Webpacker::Manifest::MissingEntryError at /meditations
> Webpacker can't find media/images/meditations/prescreen-background-large.jpg in WeMeditate/public/packs/manifest.json. Possible causes:
> 1. You want to set webpacker.yml value of compile to true for your environment
>    unless you are using the `webpack -w` or the webpack-dev-server.
> 2. webpack has not yet re-run to reflect updates.
> 3. You have misconfigured Webpacker's config/webpacker.yml file.
> 4. Your webpack configuration is not creating a manifest.

so when i change (in `image_helper.rb`):

`STATIC_IMAGE_VERSIONS[path].each do |name, width|
      srcset << "#{asset_pack_path("media/images/#{path}-#{name}.#{extension}")} #{width}w"
      webp_srcset << "#{asset_pack_path("media/images/#{path}-#{name}.webp")} #{width}w"
    end`

to 

`STATIC_IMAGE_VERSIONS[path].each do |name, width|
      srcset << "#{asset_pack_path("media/#{path}-#{name}.#{extension}")} #{width}w"
      webp_srcset << "#{asset_pack_path("media/#{path}-#{name}.webp")} #{width}w"
    end`

I am able to access the page but the image (prescreen-background-large.jpg) is missing.

**Comment by Ardnived** [comment]
So for the style of the static error page
- Could you update the font sizes and list item spacing to match the dynamic error page.
- Try to centre the entire text vertically (You can do this using [flexbox](https://philipwalton.github.io/solved-by-flexbox/demos/vertical-centering/) if you don't already know about that)
- Add a logo centred above the "Oops" text (You can use `images/header/logo.svg`)
- Change the "Oops" text to just say "We Meditate"

**Comment by Ardnived** [comment]
@Mrinalsinghal Is this branch ready for merging as far as you're concerned? I think it should be as far as I can see.

**Comment by Mrinalsinghal** [comment]
Good to go from my side

**Pull request merged**
